export const SOLICITAR_CREDITO = 'SOLICITAR_CREDITO'
export const SOLICITAR_CREDITO_EXITO = 'SOLICITAR_CREDITO_EXITO'
export const SOLICITAR_CREDITO_ERROR = 'SOLICITAR_CREDITO_ERROR'

export const CREAR_USUARIO = 'CREAR_USUARIO'
export const CREAR_USUARIO_EXITO = 'CREAR_USUARIO_EXITO'
export const CREAR_USUARIO_ERROR = 'CREAR_USUARIO_ERROR'

export const INICIO_SESION = 'INICIO_SESION'
export const INICIO_SESION_EXITO = 'INICIO_SESION_EXITO'
export const INICIO_SESION_ERROR = 'INICIO_SESION_ERROR'

export const INFORMACION_PERSONAL = 'INFORMACION_PERSONAL'
export const INFORMACION_PERSONAL_EXITO = 'INFORMACION_PERSONAL_EXITO'
export const INFORMACION_PERSONAL_ERROR = 'INFORMACION_PERSONAL_ERROR'

export const VER_CREDITO = 'VER_CREDITO'
export const VER_CREDITO_EXITO = 'VER_CREDITO_EXITO'
export const VER_CREDITO_ERROR = 'VER_CREDITO_ERROR'

export const OBTENER_CREDITO_EDITAR = 'OBTENER_CREDITO_EDITAR';
export const COMENZAR_EDICION_CREDITO = 'COMENZAR_EDICION_CREDITO';
export const CREDITO_EDITADO_EXITO = 'CREDITO_EDITADO_EXITO';
export const CREDITO_EDITADO_ERROR = 'CREDITO_EDITADO_ERROR';

